# Generated by Django 2.1.7 on 2019-03-29 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='ismanager',
            field=models.BooleanField(verbose_name='是否部门管理员'),
        ),
    ]
