# Generated by Django 2.1.7 on 2019-03-29 15:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20190329_1527'),
    ]

    operations = [
        migrations.RenameField(
            model_name='users',
            old_name='ismanager',
            new_name='is_manager',
        ),
    ]
